In [ ]:
import numpy as np
vec=np.arange(10,20,3)
print (vec)


[10 13 16 19]


In [ ]:
np.linspace(1,4,4)

array([1., 2., 3., 4.])

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([1,2])

array([[1., 1.]])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
val1 = np.arange(0,10)
val2 = val1.reshape([10])
val2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
vec = np.arange(2,5,1)
vec

array([2, 3, 4])

In [ ]:
array1 = np.arange(1,4)
array2 = np.arange(4,7)
print("array1",array1)
print("array2",array2)
print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)
print(array1**array2)

print(2*array1)

array1 [1 2 3]
array2 [4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[2 4 6]


In [ ]:
list1 = np.arange(10)
print(list1)
np.max(list1)

[0 1 2 3 4 5 6 7 8 9]


9

In [ ]:
list = [1,2,34]
list1 = list.copy()
list1[2] = 0
list1

[1, 2, 0]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
array =  np.random.randint(1,5,20)

In [ ]:
np.save('/content/drive/MyDrive/Colab Notebooks/myarray',array)

In [ ]:
value = np.load('/content/drive/MyDrive/Colab Notebooks/myarray.npy')
print(value)
type(value) 

[3 4 2 1 3 2 2 1 4 3 1 1 2 3 2 1 2 4 3 3]


numpy.ndarray

In [1]:
import pandas as pd


In [ ]:
array = [1 ,2,3]
nparray = np.arange(1,5)
print(array)
print(nparray)

[1, 2, 3]
[1 2 3 4]


In [ ]:
col1 = pd.Series(array)
col2 = pd.Series(nparray)

print(pd.DataFrame({"col1":col1, "col2":col2}))

   col1  col2
0   1.0     1
1   2.0     2
2   3.0     3
3   NaN     4


In [ ]:
array = np.random.randint(1,20,5)
data = pd.DataFrame({"name":array})
data['age'] = [1,2,3,4,5]
# print(array)
print( data)

# print("np array",array[1])
print(data.iloc[1,0])

   name  age
0    16    1
1    12    2
2    17    3
3     7    4
4    18    5
12


In [ ]:
matrix = np.arange(1,10).reshape(3,3)
matrix[0:2,1:2] = 0
print(matrix)

[[1 0 3]
 [4 0 6]
 [7 8 9]]


In [ ]:
import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print (array2 == array1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
import numpy as np
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
data_customer = pd.DataFrame({'customer' : [101,102,103,104],
              'category' : ['cat2','cat2','cat1','cat3'],
              'important' : ['yes','no','yes','yes'],
              'sales' : [123,52,214,663]})
data_customer.groupby(['customer'])['sales'].mean()

customer
101    123.0
102     52.0
103    214.0
104    663.0
Name: sales, dtype: float64

In [ ]:
value = np.arange(0,10);
value[0:7] = 5
value

array([5, 5, 5, 5, 5, 5, 5, 7, 8, 9])